### ISSUE TITLE
Question RE file transfers between PHP processes without browser

### ISSUE THREAD

**Issue by wesyah234** [cubiclesoft/php-cool-file-transfer#2]
I've been trying to find a good solution for sending a file from a cron job written in PHP running on server A, to another server B.  Server B runs a web application so it could host a PHP endpoint that the script on server A could connect to.

I can do this with small files using Curl or Guzzle on Server A, and then handling it as a form post upload on Server B, but I need it to work for any size files (ie. very large).

It seems like what you have here might have some utility for this use case... what do you think?

Thanks!

**Comment by cubiclesoft** [comment]
Cool File Transfer is a mechanism that forms a link between two web browsers via a fairly novel/hacky approach to link the two endpoints together.  That is, the server that both browsers visit acts as a tunnel for the data via an internal TCP/IP server each upload sets up and uses a SQLite database to find the correct server to connect to.  What makes it "cool" is that there is no data storage requirement.  What you want is something completely different.

If you can, use built-in tools like `scp`, which talk SSH/SFTP.  I also have a command-line tool called [PHP SSH Tools](https://github.com/cubiclesoft/php-ssh/) for scripting purposes but I have no idea if phpseclib has any issues with large files.  Also, if the file is more than 50MB, you'll probably want chunked uploading instead of an all-or-nothing solution.

If you can't use something like the aforementioned to transfer your files directly over SSH/SFTP or just want chunked uploads, I recommend [Ultimate Web Scraper Toolkit](https://github.com/cubiclesoft/ultimate-web-scraper) for your use-case.  It can send as much (or as little) POST data as you want in `multipart/form-data` format.  Unlike cURL and Guzzle, Ultimate Web Scraper is actually designed to offer a generic HTTP client architecture because its primary objective is scraping content from badly configured, temperamental environments.  Throw in connection/upload retries for a more robust solution that can survive temporary network conditions.  Use the right tool for the job and it'll go a lot easier.

The Standard HTTP `Range` header (and `Accept-Range: bytes` header from the server) can be used to start a data transfer at any point, allowing for multiple requests to be made that uploads files in chunks.  The server side parses the `Range` header (and any other relevant headers such as session ID) to figure out where in the file to start writing data.

You'll want to split very large file uploads into three parts:  Initialize upload, actual data (multiple requests), finalize upload.

Hopefully something in the above helps to solve the problem.  Closing this issue.

**Comment by wesyah234** [comment]
Thank you for all the suggestions, I'll look at all of them!  BTW I looked at your web scraper toolkit and it seems really cool and useful for many other things too.
